version: '3.8'

services:
  mvcapp:
    build:
      context: .
      dockerfile: TresDos/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TresDos;User Id=sa;Password=5qL@5d5;Encrypt=false;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - DB_PASSWORD=5qL@5d5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "5qL@5d5"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: